### ISSUE TITLE
Request: config option to allow bosses in mob imprisonment tool

### ISSUE THREAD

**Issue by freopt** [eve0415/IFPatcher#10]
Currently the mob imprisonment tool is hardcoded to not allow bosses, a config option to change that would be cool. Presumably you could still use the blacklist from this mod to keep balance.

**Comment by eve0415** [comment]
Implemented as of 5f319aed0c5554025e9cc0de4ad92e30b0869f2e.

I've uploaded a new version (2.3.0) to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ifpatcher).
You might need to wait for few minutes before it will show up.
