### ISSUE TITLE
[Request] Boss Capture must be enabled by config option

### ISSUE THREAD

**Issue by anabsolutesloth** [eve0415/IFPatcher#11]
Not every pack will want bosses to be capturable, and this being forced requires the blacklist to contain mobs classified as bosses, it's not the largest issue, but it can definitely be a bother.

**Comment by eve0415** [comment]
Hi. Sorry for the delay.

New option to disable boss capturing has been implemented as of ea693db922c7f459024735319b75840775fae256.

[v2.4.0](https://github.com/eve0415/IFPatcher/releases/tag/v2.4.0) has been published and it should be available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ifpatcher) in few minutes.
