### ISSUE TITLE
Unintended behavior between Plant Interactor and SimpleHarvest

### ISSUE THREAD

**Issue by MasterEnderman** [eve0415/IFPatcher#12]
SimpleHarvest: https://www.curseforge.com/minecraft/mc-mods/simpleharvest

When installing SimpleHarvest and setting up a field of crops which gets harvested by a plant interactor the growth stage of the crops doesn't reset. This lets the interactor harvest an infinite amount of crops without having to wait for them to grow.
This has been a longstanding issue in [Antimatter Chemistry](https://www.curseforge.com/minecraft/modpacks/antimatter-chemistry) a modpack currently maintained by me. I recent switched to another "right-click-to-harvest-crop" mod named [Simple Harvest](https://www.curseforge.com/minecraft/mc-mods/simple-harvest) (yes the name is almost the same), but now the interactor doesn't work at all.

I hope this can be fixed in a future update. Thanks for looking into it. If any further information is required please let me know.

**Comment by eve0415** [comment]
Thanks for the report. After conducting some research, it appears that this issue does not originate from Industrial Foregoing.
Also, [simpleharvest](https://github.com/TehNut-Mods/Harvest) looks like it is EoL too.

As for `Simple Harvest`, the crops are added directly to the player's inventory, thus does not have compatibility with those machines`

There is nothing much I can do other then to patch those mods

**Comment by MasterEnderman** [comment]
After some research I found out that this issue was reported on the GitHub of SimpleHarvest ages ago. https://github.com/TehNut-Mods/Harvest/issues/16

At this point it may be easier for me to fork it and try to fix it on their side.
