### ISSUE TITLE
TFCTech Unofficial adds Rubber, but it doesn't allow crafting Industrial Foregoing's Plastic.

### ISSUE THREAD

**Issue by MagmaSlime123** [eve0415/IFPatcher#4]
Since Industrial Foregoing for 1.12 is EOL, I'm reporting this here. Would've reported this to TFCTech Unofficial also, but I think its dead, not sure.

Rubber from TFCTech Unofficial cannot be used to make Plastic from Industrial Foregoing since IF's machines refuse to let other Rubber items in its machines (Tried adding TFCTech Unofficial's Rubber into the OreDict, still didn't work).

If you need screenshots, let me know.

TFC = TerraFirmaCraft, btw.

**Comment by eve0415** [comment]
Hey, thank you for opening the issues.

What's the machine's name and what exactly do you want to do?

**Comment by MagmaSlime123** [comment]
Sorry for the late response. I don't know why IF is forcing Ender IO's Alloy Smelter to be used, I never changed anything related to this. But basically, allow any Rubber from any mod to be used to craft IF Plastic.

If your using TFC and TFCTech Unofficial, its Rubber could be smelted into IF Plastic via TFC's Heating recipe system, which as shown below, IF normally doesn't allow.

![2022-04-14_06 00 28](https://user-images.githubusercontent.com/51277766/163395785-2f0ff4df-28a7-43b7-a69f-0226ce49e83d.png)

![2022-04-14_06 03 46](https://user-images.githubusercontent.com/51277766/163396414-34470c5f-24e4-426b-9d2e-38f66c24a04b.png)

**Comment by eve0415** [comment]
I'll check if rubber from other mods can be used to make plastic

**Comment by MagmaSlime123** [comment]
Thanks. 

As said, since IF adds pink slime, Tinkers Construct is adding tools made of it that aren't craft-able, for some reason.

**Comment by eve0415** [comment]
Hey, sry for late reply

> As said, since IF adds pink slime, Tinkers Construct is adding tools made of it that aren't craft-able, for some reason.

This behavior is intended; you need other mod that enables that. See [PlusTic](https://github.com/Landmaster/PlusTiC)

**Comment by MagmaSlime123** [comment]
Oh. Didn't know.

**Comment by eve0415** [comment]
Doing more research on this, I couldn't find other mods that has rubber except for GregTech. I also think rubber from IF and TFC is kind of different (meaning I won't be patching this unfortunately).
I'll leave the issue opened in case you have something to say, if not it'll be closed

**Comment by MagmaSlime123** [comment]
Ah, alright.

I don't know why IF doesn't just add its Rubber to the OreDict and allow Plastic creation with other mods Rubber by default. 
Very annoying.
