### ISSUE TITLE
Mob imprisonment tool blacklist

### ISSUE THREAD

**Issue by freopt** [eve0415/IFPatcher#5]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/559
would there be a way to implement this?
there's the thing linked in the issue but I don't really want to install a whole mixin loader

**Comment by eve0415** [comment]
I need to look more into it but I believe I can implement that.
However I don't have enough time to work on this recently so I need some time

**Comment by eve0415** [comment]
Hi. I have implemented this feature and version 2.0.0 is available now.
You might need to wait for few minutes before it will show on [CurseForge site](https://www.curseforge.com/minecraft/mc-mods/ifpatcher).

Happy minecrafting!
