### ISSUE TITLE
Latex Processor Eats buckets

### ISSUE THREAD

**Issue by TotallyNotAGhost** [eve0415/IFPatcher#7]
reposting from tekkit 2 bug tracker as requested from xJon

Basic details

Are you using a legitimate Minecraft account?: yes
Are you using Java 8, 64-bit?: yes
Did you add any additional mods: no
Crash/latest log link (if applicable): not applicable
Describe the issue

if a latex processing unit has less than a bucket left of room in it's latex tank then putting a latex bucket in there will destroy the bucket.

https://www.youtube.com/watch?v=-VM4McAUCEg

**Comment by eve0415** [comment]
Patched as of ebde988aacbd2126074cd63636a517f3e3b1fe04.

I've uploaded a new version to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ifpatcher).
You might need to wait for few minutes before it will show up.
