### ISSUE TITLE
[Request] Mob Imprisonment Tool Blacklist Wildcard support

### ISSUE THREAD

**Issue by anabsolutesloth** [eve0415/IFPatcher#8]
In larger modpacks, that blacklist can become extremely long, and some mods you may just want to blacklist all of their mobs anyway.

**Comment by eve0415** [comment]
Implemented as of 3a731942ca63e9f454e6a8f960b50655047875d4.

I've uploaded a new version (2.2.0) to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ifpatcher).
You might need to wait for few minutes before it will show up.

**Comment by anabsolutesloth** [comment]
holy wow, i did not expect action on this that quick!
