### ISSUE TITLE
HEI and Industrial Forgoing Crash

### ISSUE THREAD

**Issue by bluesillybeard** [eve0415/IFPatcher#9]
Basic details
- Using a legit Microsoft account
- Java 19 64 bit, on Manjaro Linux
- Tekkit 2 modpack, in case that helps
- crash log: https://mclo.gs/DKuPwUM

How to reproduce
- search 'dust' into HEI
- click on silver dust
- click on Fluid Sieving Machine (to the right of the Crafting Table)
- crash

**Comment by eve0415** [comment]
Duplicate of #2
